package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ============================================================================
// generate-adapter 命令测试
// ============================================================================

func TestGenerateAdapterBasic(t *testing.T) {
	// 创建临时目录
	tmpDir := t.TempDir()

	// 创建测试输入文件
	inputContent := `package testpkg

type Book struct {
	Title  string  ` + "`" + `item:"title,required"` + "`" + `
	Author string  ` + "`" + `item:"author,default=Unknown"` + "`" + `
	Price  float64 ` + "`" + `item:"price"` + "`" + `
	ISBN   string  ` + "`" + `json:"isbn"` + "`" + `
}
`
	inputFile := filepath.Join(tmpDir, "items.go")
	if err := os.WriteFile(inputFile, []byte(inputContent), 0644); err != nil {
		t.Fatalf("failed to write input file: %v", err)
	}

	// 运行生成器
	outputFile := filepath.Join(tmpDir, "book_adapter_gen.go")
	err := runGenerateAdapter([]string{
		"-type=Book",
		"-input=" + inputFile,
		"-output=" + filepath.Base(outputFile),
	})
	if err != nil {
		t.Fatalf("generate-adapter failed: %v", err)
	}

	// 验证输出文件存在
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("failed to read output file: %v", err)
	}

	code := string(content)

	// 验证生成的代码包含关键内容
	checks := []string{
		"Code generated by scrapy-go generate-adapter; DO NOT EDIT",
		"package testpkg",
		"type BookAdapter struct",
		"func NewBookAdapter",
		"func (a *BookAdapter) Item() any",
		"func (a *BookAdapter) FieldNames() []string",
		"func (a *BookAdapter) GetField(name string) (any, bool)",
		"func (a *BookAdapter) SetField(name string, value any) error",
		"func (a *BookAdapter) HasField(name string) bool",
		"func (a *BookAdapter) AsMap() map[string]any",
		"func (a *BookAdapter) Len() int",
		"func (a *BookAdapter) FieldMeta(name string) item.FieldMeta",
		`"title"`,
		`"author"`,
		`"price"`,
		`"isbn"`,
		`"required"`,
		`"default"`,
		"var _ item.ItemAdapter",
	}

	for _, check := range checks {
		if !strings.Contains(code, check) {
			t.Errorf("generated code missing: %q", check)
		}
	}
}

func TestGenerateAdapterMissingType(t *testing.T) {
	err := runGenerateAdapter([]string{"-input=test.go"})
	if err == nil {
		t.Error("expected error for missing -type")
	}
}

func TestGenerateAdapterMissingInput(t *testing.T) {
	// 清除 GOFILE 环境变量
	os.Unsetenv("GOFILE")
	err := runGenerateAdapter([]string{"-type=Book"})
	if err == nil {
		t.Error("expected error for missing input")
	}
}

func TestGenerateAdapterNonexistentFile(t *testing.T) {
	err := runGenerateAdapter([]string{"-type=Book", "-input=/nonexistent/file.go"})
	if err == nil {
		t.Error("expected error for nonexistent file")
	}
}

func TestGenerateAdapterNonexistentType(t *testing.T) {
	tmpDir := t.TempDir()
	inputContent := `package testpkg

type Other struct {
	Name string
}
`
	inputFile := filepath.Join(tmpDir, "items.go")
	os.WriteFile(inputFile, []byte(inputContent), 0644)

	err := runGenerateAdapter([]string{"-type=Book", "-input=" + inputFile})
	if err == nil {
		t.Error("expected error for nonexistent type")
	}
}

func TestParseItemTagFromRaw(t *testing.T) {
	tests := []struct {
		rawTag    string
		name      string
		required  bool
		defVal    string
		omitempty bool
	}{
		{`item:"title,required"`, "title", true, "", false},
		{`item:"author,default=Unknown"`, "author", false, "Unknown", false},
		{`item:"host,required,default=localhost"`, "host", true, "localhost", false},
		{`json:"isbn"`, "isbn", false, "", false},
		{`item:"field,omitempty"`, "field", false, "", true},
		{`item:"name" json:"name"`, "name", false, "", false},
	}

	for _, tt := range tests {
		name, required, defVal, omitempty, _ := parseItemTagFromRaw(tt.rawTag)
		if name != tt.name {
			t.Errorf("tag=%q: name=%q, want %q", tt.rawTag, name, tt.name)
		}
		if required != tt.required {
			t.Errorf("tag=%q: required=%v, want %v", tt.rawTag, required, tt.required)
		}
		if defVal != tt.defVal {
			t.Errorf("tag=%q: default=%q, want %q", tt.rawTag, defVal, tt.defVal)
		}
		if omitempty != tt.omitempty {
			t.Errorf("tag=%q: omitempty=%v, want %v", tt.rawTag, omitempty, tt.omitempty)
		}
	}
}

func TestExtractTagValue(t *testing.T) {
	tests := []struct {
		rawTag string
		key    string
		want   string
	}{
		{`item:"title,required"`, "item", "title,required"},
		{`json:"name" item:"title"`, "item", "title"},
		{`json:"name,omitempty"`, "json", "name,omitempty"},
		{`json:"name"`, "item", ""},
	}

	for _, tt := range tests {
		got := extractTagValue(tt.rawTag, tt.key)
		if got != tt.want {
			t.Errorf("extractTagValue(%q, %q) = %q, want %q", tt.rawTag, tt.key, got, tt.want)
		}
	}
}
